services:
  bot:
    build:
      network: host
      context: .
    network_mode: host
    restart: always
    environment:
      REDIS_PORT: ${REDIS_PORT}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      OPERATOR_TOKEN: ${OPERATOR_TOKEN}

      ADMINS: ${ADMINS}
      ADMINS_1: ${ADMINS_1}
      ADMINS_2: ${ADMINS_2}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_ECHO_LOG: ${DB_ECHO_LOG}

      SERVICE_PORT: ${SERVICE_PORT}
      SERVICE_TOKEN: ${SERVICE_TOKEN}
  redis:
    image: redis:8.2
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data: